clear 
clc
close all
tic
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% NCKU Tainan, BME Department,2020/04/16
%% Example: 028 DIC_T1_Z1.jpg to 028 DIC_T1_Z20.jpg <=> ..._Z1.jpg to ..._Z20.jpg => Slice_pic_num = 20
%% Example: 028 DIC_T1_Z1.jpg to 028 DIC_T96_Z1.jpg <=> ..._T1... to ..._T96... => Pic_begin = 1 && Pic_end = 96
%% Parameter
input_Folder_name = {'Exp1','Exp2'}; % Name of Folder store Images
Slice_pic_num = 20; % Number of sub-pictures
CreateVideo = 'n'; % Press y to create video, if not press n
AnalyzeData = 'n'; % Press y to analyze data, if not press n
Macrofile_name = 'Macro'; % name of Macro code % Don't change this
dt = 30; % Duration % Don't change this
Rate = 10; % set frame rate for video % Don't change this
%% Process
for i = 1:length(input_Folder_name)
    if length(Slice_pic_num) == 1
        Pic_begin = 1; % Picture begin
        Pic_end = length(dir(['Input\',input_Folder_name{i},'\*.jpg']))/Slice_pic_num; % Picture end
        Process(input_Folder_name{i},...
            ['Ouput_',input_Folder_name{i}],...
            Slice_pic_num,...
            Pic_begin,...
            Pic_end,...
            Macrofile_name,...
            CreateVideo,...
            AnalyzeData,...
            dt,Rate)
    else
        Pic_begin = 1; % Picture begin
        Pic_end = length(dir(['Input\',input_Folder_name{i},'\*.jpg']))/Slice_pic_num(i); % Picture end
        Process(input_Folder_name{i},...
            ['Ouput_',input_Folder_name{i}],...
            Slice_pic_num,...
            Pic_begin,...
            Pic_end,...
            Macrofile_name,...
            CreateVideo,...
            AnalyzeData,...
            dt,Rate)
    end
end
toc
