run("Images to Stack", "name=Stack title=[] use");
run("Z Project...", "projection=[Standard Deviation]");
run("8-bit");
run("Enhance Contrast...", "saturated=0.3");
setAutoThreshold("Li dark");
//run("Threshold...");
//setThreshold(46, 255);
setOption("BlackBackground", false);
run("Convert to Mask");
run("Dilate");
run("Median...", "radius=6");
run("Fill Holes");
run("Set Scale...", "distance=98 known=50 unit=um");
run("Specify...", "width=800 height=800 x=290 y=100");
run("Crop");
run("Analyze Particles...", "size=1.04-Infinity display");
//saveAs("Results", "G:/ImageP/Another/Results.csv");
selectWindow("Stack");
close();
selectWindow("STD_Stack");
